### ISSUE TITLE
False positive with 'contains' (?)

### ISSUE THREAD

**Issue by Tset-Noitamotua** [asyrjasalo/RESTinstance#63] opened 2019-02-25 19:19 UTC
Not sure if this is a false positive

![image](https://user-images.githubusercontent.com/5635462/53362197-e76b5180-3939-11e9-9ed4-1384be9cba57.png)

I am sure that `{'bar': 0, 'foo': 123}` does not occur in the response. So I was expecting the test to fail because of the validation.

Am I doing something wrong?

**Comment by Tset-Noitamotua** [comment] 2019-02-25 19:33
when I try `contains="somestring"` then it fails like this

![image](https://user-images.githubusercontent.com/5635462/53362964-ad02b400-393b-11e9-8074-0b6bf4bc47e1.png)

Now I wonder does 'contains' only check if what I pass is an object or boolean?

**Comment by Tset-Noitamotua** [comment] 2019-04-04 22:42
>**contains**
>
>The value of this keyword MUST be a valid JSON Schema.
>
>An array instance is valid against "contains" if at least one of its elements is valid against the given schema.

http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.6

**Comment by asimell** [comment] 2021-05-19 07:17
Hi @Tset-Noitamotua,

This sounds like a bug for sure, but needs further investigation. We'll come back to this once we can see if it actually is a bug.

**Comment by asimell** [comment] 2021-05-31 07:10
Hi @Tset-Noitamotua ,

After doing some digging on this, it looks like `contains` only validates the output schema. This means that if your query returns

```
{ [ {"item1": "value1"}, {"item2": "value2"} ] }
```

you can check for example `contains={"type": "object"}`, but not whether the array actually contains an item that matches your query. For this you should implement your own logic.

Also based on http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.4 (your /latest redirects here). It doesn't have a `contains` validation anymore, but instead 2 validations `maxContains` and `minContains`. However, these aren't supported by [Python Jsonschema](https://github.com/Julian/jsonschema/blob/main/jsonschema/validators.py#L391).

**Comment by asimell** [comment] 2021-07-01 07:06
According to JSONSchema documentation, this is a feature of JSONSchema and not a bug in the library, we're closing this issue.

**Closed by asimell** 2021-07-01 07:06 UTC
Labels: bug
